# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    env_file: ".env"
    expose:
      - 8080/tcp
    ports:
      - 8080:8080/tcp
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:8888
    depends_on:
      - ollama-server
  ollama-server:
    image: ollama/ollama
    env_file: ".env"
    container_name: ollama-server
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:11434
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      host_ip: ${host_ip}
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
